#!/usr/bin/env bash

force=""
prefix="<none>"

usage() {
    printf "Cleans dangling and <none> images generated in a build process if called with no args, "
    printf "or every image starting by the first arg if passed\n"
    printf "Usage: docker-clean [-f] [-p <prefix>]\n"
    printf "\t-f, forces the removal\n"
    printf "\t-p <prefix> images with name starting with prefix will be deleted\n"
}

while getopts ":fp:" opt; do
    case $opt in
        f) force="-f";;
        p) prefix="$OPTARG";;
        :) usage; exit 1;;
    esac
done


docker rmi $force $(docker image ls | grep "$prefix" | awk '{print $3}')
