#! /usr/bin/env bash

usage() {
    printf "Cleans dangling and <none> images generated in a build process if called with no args, "
    printf "or every image starting by the first arg if passed\n"
    printf "Usage: docker-clean [prefix]\n"
    printf "\tprefix: images with name starting with prefix will be deleted\n"
}

if [ "$#" -gt 1 ]; then
    printf "docker-clean: wrong number of args\n\n"
    usage
    exit
fi


case $# in
    0) docker rmi $(docker image ls | grep "<none>" | awk '{print $3}');;
    1) docker rmi $(docker image ls | grep "$1" | awk '{print $3}')
esac

